In [1]:
import pandas as pd
df = pd.read_csv('train.csv')
df.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [2]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [3]:
cols_to_delete = ['Id', 'MoSold', 'Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature', 'Utilities', 'Condition2', ]
df.drop(cols_to_delete,axis='columns',inplace=True)
df.head(10)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,Reg,Lvl,Inside,Gtl,CollgCr,...,61,0,0,0,0,0,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,Reg,Lvl,FR2,Gtl,Veenker,...,0,0,0,0,0,0,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,IR1,Lvl,Inside,Gtl,CollgCr,...,42,0,0,0,0,0,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,IR1,Lvl,Corner,Gtl,Crawfor,...,35,272,0,0,0,0,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,IR1,Lvl,FR2,Gtl,NoRidge,...,84,0,0,0,0,0,2008,WD,Normal,250000
5,50,RL,85.0,14115,Pave,IR1,Lvl,Inside,Gtl,Mitchel,...,30,0,320,0,0,700,2009,WD,Normal,143000
6,20,RL,75.0,10084,Pave,Reg,Lvl,Inside,Gtl,Somerst,...,57,0,0,0,0,0,2007,WD,Normal,307000
7,60,RL,NaN,10382,Pave,IR1,Lvl,Corner,Gtl,NWAmes,...,204,228,0,0,0,350,2009,WD,Normal,200000
8,50,RM,51.0,6120,Pave,Reg,Lvl,Inside,Gtl,OldTown,...,0,205,0,0,0,0,2008,WD,Abnorml,129900
9,190,RL,50.0,7420,Pave,Reg,Lvl,Corner,Gtl,BrkSide,...,4,0,0,0,0,0,2008,WD,Normal,118000

In [4]:
# Fillna with max value
def fillna_with_maxval(col):
    global df
    df[col].fillna(df[col].value_counts().idxmax(),inplace=True)

In [5]:
def encode_dummies(col):
    global df
    df[col] = df[col].apply(lambda x: x + col)
    dummies = pd.get_dummies(df[col])
    df = pd.concat([df, dummies],axis='columns')
    df.drop([col],axis='columns',inplace=True)

In [6]:
def fillnacol(col):
    global df
    df[col].fillna(df[col].mean(),inplace=True)

In [7]:
cols_to_encode = ['MSZoning', 'Street', 'LotShape', 'LandContour', 'LotConfig', 'LandSlope', 'Neighborhood', 
                  'Condition1', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd',
                  'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
                  'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 
                  'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'SaleType', 'SaleCondition',
                 ]
cols_to_fillna = ['LotFrontage', 'MasVnrArea', 'GarageYrBlt', 
                 ]
cols_to_fillna_with_maxval = ['MasVnrType', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 
                              'Electrical', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'MSZoning',
                              'Exterior1st', 'Exterior2nd', 'KitchenQual', 'Functional', 'SaleType', 'SaleCondition', 
                             ]

In [8]:
for col in cols_to_fillna_with_maxval:
    fillna_with_maxval(col)
for col in cols_to_encode:
    encode_dummies(col)
for col in cols_to_fillna:
    fillnacol(col)

In [9]:
df

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,ConSaleType,NewSaleType,OthSaleType,WDSaleType,AbnormlSaleCondition,AdjLandSaleCondition,AllocaSaleCondition,FamilySaleCondition,NormalSaleCondition,PartialSaleCondition
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,0,0,0,1,0,0,0,0,1,0
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,0,0,0,1,0,0,0,0,1,0
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,0,0,0,1,0,0,0,0,1,0
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,0,0,0,1,1,0,0,0,0,0
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,62.0,7917,6,5,1999,2000,0.0,0,0,...,0,0,0,1,0,0,0,0,1,0
1456,20,85.0,13175,6,6,1978,1988,119.0,790,163,...,0,0,0,1,0,0,0,0,1,0
1457,70,66.0,9042,7,9,1941,2006,0.0,275,0,...,0,0,0,1,0,0,0,0,1,0
1458,20,68.0,9717,5,6,1950,1996,0.0,49,1029,...,0,0,0,1,0,0,0,0,1,0
1459,20,75.0,9937,5,6,1965,1965,0.0,830,290,...,0,0,0,1,0,0,0,0,1,0

In [10]:
def print_out(col):
    global df
    print(df[col].isna().sum())
    print(df[col].unique())
    print(df[col].value_counts(dropna=False))
# print_out("Electrical")

In [11]:
X = df.drop(['SalePrice'],axis='columns')
y = df['SalePrice']

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [13]:
from sklearn.linear_model import LinearRegression
linreg_clf = LinearRegression()

In [14]:
linreg_clf.fit(X_train,y_train)
linreg_clf.score(X_test,y_test)

0.7797807952372299

In [15]:
dftest = pd.read_csv('test.csv')
dftest

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [16]:
id_col = dftest['Id']
id_col

0       1461
1       1462
2       1463
3       1464
4       1465
        ...
1454    2915
1455    2916
1456    2917
1457    2918
1458    2919
Name: Id, Length: 1459, dtype: int64

In [17]:
dftest.drop(cols_to_delete,axis='columns',inplace=True)
dftest.head(10)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,YrSold,SaleType,SaleCondition
0,20,RH,80.0,11622,Pave,Reg,Lvl,Inside,Gtl,NAmes,...,140,0,0,0,120,0,0,2010,WD,Normal
1,20,RL,81.0,14267,Pave,IR1,Lvl,Corner,Gtl,NAmes,...,393,36,0,0,0,0,12500,2010,WD,Normal
2,60,RL,74.0,13830,Pave,IR1,Lvl,Inside,Gtl,Gilbert,...,212,34,0,0,0,0,0,2010,WD,Normal
3,60,RL,78.0,9978,Pave,IR1,Lvl,Inside,Gtl,Gilbert,...,360,36,0,0,0,0,0,2010,WD,Normal
4,120,RL,43.0,5005,Pave,IR1,HLS,Inside,Gtl,StoneBr,...,0,82,0,0,144,0,0,2010,WD,Normal
5,60,RL,75.0,10000,Pave,IR1,Lvl,Corner,Gtl,Gilbert,...,157,84,0,0,0,0,0,2010,WD,Normal
6,20,RL,NaN,7980,Pave,IR1,Lvl,Inside,Gtl,Gilbert,...,483,21,0,0,0,0,500,2010,WD,Normal
7,60,RL,63.0,8402,Pave,IR1,Lvl,Inside,Gtl,Gilbert,...,0,75,0,0,0,0,0,2010,WD,Normal
8,20,RL,85.0,10176,Pave,Reg,Lvl,Inside,Gtl,Gilbert,...,192,0,0,0,0,0,0,2010,WD,Normal
9,20,RL,70.0,8400,Pave,Reg,Lvl,Corner,Gtl,NAmes,...,240,0,0,0,0,0,0,2010,WD,Normal

In [18]:
def fillna_with_maxval_dftest(col):
    global dftest
    dftest[col].fillna(dftest[col].value_counts().idxmax(),inplace=True)

In [19]:
def encode_dummies_dftest(col):
    global dftest
    dftest[col] = dftest[col].apply(lambda x: x + col)
    dummies = pd.get_dummies(dftest[col])
    dftest = pd.concat([dftest, dummies],axis='columns')
    dftest.drop([col],axis='columns',inplace=True)

In [20]:
def fillnacol_dftest(col):
    global dftest
    dftest[col].fillna(dftest[col].mean(),inplace=True)

In [21]:
for col in cols_to_fillna_with_maxval:
    fillna_with_maxval_dftest(col)
for col in cols_to_encode:
    encode_dummies_dftest(col)
for col in cols_to_fillna:
    fillnacol_dftest(col)

In [22]:
for col in dftest.columns:
    if dftest[col].isna().sum() > 0:
        dftest[col].fillna(dftest[col].mean(),inplace=True)

In [23]:
dftest

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,ConSaleType,NewSaleType,OthSaleType,WDSaleType,AbnormlSaleCondition,AdjLandSaleCondition,AllocaSaleCondition,FamilySaleCondition,NormalSaleCondition,PartialSaleCondition
0,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,0,0,0,1,0,0,0,0,1,0
1,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,0,0,0,1,0,0,0,0,1,0
2,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,0,0,0,1,0,0,0,0,1,0
3,60,78.0,9978,6,6,1998,1998,20.0,602.0,0.0,...,0,0,0,1,0,0,0,0,1,0
4,120,43.0,5005,8,5,1992,1992,0.0,263.0,0.0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,160,21.0,1936,4,7,1970,1970,0.0,0.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1455,160,21.0,1894,4,5,1970,1970,0.0,252.0,0.0,...,0,0,0,1,1,0,0,0,0,0
1456,20,160.0,20000,5,7,1960,1996,0.0,1224.0,0.0,...,0,0,0,1,1,0,0,0,0,0
1457,85,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,...,0,0,0,1,0,0,0,0,1,0
1458,60,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,...,0,0,0,1,0,0,0,0,1,0

In [24]:
diff_col = []

for col in df.columns:
    if col not in dftest.columns:
        diff_col.append(col)

diff_col

['SalePrice',
 '2.5FinHouseStyle',
 'ClyTileRoofMatl',
 'MembranRoofMatl',
 'MetalRoofMatl',
 'RollRoofMatl',
 'ImStuccExterior1st',
 'StoneExterior1st',
 'OtherExterior2nd',
 'FloorHeating',
 'OthWHeating',
 'MixElectrical',
 'ExGarageQual']